project:
  type: website
  output-dir: docs

description-meta: "Michael Asger Andersen, MD, PhD - Clinical Pharmacologist & Physician-Researcher"
author-meta: "Michael Asger Andersen"

website:
  title: "Michael Asger Andersen"
  image: "files/images/cph_foto_michael.jpg"
  description: "Clinical Pharmacologist & Physician-Researcher"

  navbar:
    background: light
    left:
      - text: About
        href: index.qmd
      - text: Research & Projects
        href: projects.qmd
      - text: Publications
        href: publications.qmd
      - text: Teaching & Mentorship
        href: teaching.qmd
      - text: CV (PDF)
        href: cv-michael-andersen.pdf
        target: _blank
      - text: Contact
        href: contact.qmd

    right:
      - icon: github
        href: https://github.com/masger
        target: _blank
      - text: "{{< ai orcid >}}"
        href: https://orcid.org/0000-0001-9729-9974
        target: _blank
      - text: "{{< ai google-scholar >}}"
        href: https://scholar.google.dk/citations?hl=da&user=Bu8uQCAAAAAJ
        target: _blank

  page-footer:
    left: "Michael Asger Andersen &copy; <script>document.write(new Date().getFullYear())</script>"
    right:
      - icon: github
        href: https://github.com/masger
        target: _blank
      - text: "{{< ai orcid >}}"
        href: https://orcid.org/0000-0001-9729-9974
        target: _blank

  search:
    location: navbar
    type: textbox

  open-graph: true
  twitter-card: true
  site-url: "https://masger.github.io"

format:
  html:
    theme:
      light: cosmo
    css: styles.css
    toc: true
    footnotes-hover: true
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    include-in-header: "files/includes/_academic.qmd"
