---
title: "Type af bivirkning for UFL kronik"
output:
  html_document
---

Tabellen præsenterer en oversigt over forskellige typer af lægemiddelreaktioner, klassificeret ved hjælp af mnemoteknikken A-F, og skal bruges til identificering og underbyggelse af bivirkninger som beskrevet i kronik i Ugeskrift for Læger.

| Type (Mnemoteknik) | Kendetegn | Eksempel | Håndtering |
| --- | --- | --- | --- |
| A (Augmented) | - Dosisafhængig<br>- Farmakologisk reaktion på lægemiddel<br>- Forudsigelig, ofte fundet i godkendelsesstudierne<br>- Hyppig<br>- Sjælden alvorlig | - Warfarin – blødning<br>- Insulin – hypoglykæmi<br>- β-blokkere – bradykardi | - Reducer dosis<br>- Pauser behandling<br>- Overvej interaktioner medførende øget koncentration i blodet |
| B (Bizar) | - Dosisuafhængig<br>- Uforudsigelig<br>- Relativt ofte alvorlig<br>- Sjælden | - Immunologiske/allergiske: Penicillin - Anafylaksi<br>- Idiosynkratiske: Amoxicillin – lægemiddel induceret leverskade (DILI) | - Seponer og undgå fremtidig behandling (CAVE) |
| C (Chronic) | - Ofte relateret til den kumulative dosis | - Glukokortikoider – Osteoporose<br>- Platin-baserede lægemidler – neurotoksicitet | - Reducer dosis eller tilbagehold behandling |
| D (Delayed) | - Kommer forsinket efter påbegyndt behandling<br>- Sjælden | - Thiazider – spinocellulært carcinom<br>- Bisfosfonater- kæbeosteonekrose<br>- Neuroleptika – tardiv dyskinesi | - Kan sjældent behandles |
| E (End of use) | - Opstår hurtigt efter endt behandling | - Protonpumpe-hæmmere – rebound fænomen med øget syreproduktion<br>- Benzodiazepiner – eks.<br>- angst, søvnforstyrrelser, agitation | - Re-introduktion og langsom udtrapning |
| F (Failure of treatment) | - Genetik<br>- Hyppig, dosisafhængig<br>- Lægemiddel-interaktioner | - Digoxin - Manglende effekt ved indtag af perikon.<br>- Nitrater - Udvikling af tolerance | - Øg dosis<br>- Overvej interaktioner medførende lavere koncentration i blodet |

