---
title: "Welcome"
output:
  html_document:
    includes:
      in_header: cover.html
---

<br><br>  
I am a medical doctor at CLL-Lab at Rigshospitalet. My research field are chronic lymphocytic leukemia and pneumococcal disease, where I study the how different pathogens are associated with chronic lymphocytic leukemia. In general, I am interested in questions like:

- How do antimicrobial usage change in the years before chronic lymphocytic leukemia diagnosis? 
- Whcih risk factors are important for the increased risk of infections?
- What is the best pneumococcal vaccine strategy for patients with chronic lymphocytic leukemia?
- How does lymphocytosis develop before the diagnosis?
- Etc.  

To answer these questions, I rely on a mix of tools that including classical survival routines, generalized additive models and I am a huge fan of the [**data.table**](https://rdatatable.gitlab.io/data.table/). In addition, I use the [**heaven**](https://github.com/tagteam/heaven) package for fast routines for the Danish health registries. 

Alongside my regular research, I spend quite a lot time playing lego with my son, watching movies and playing disc golf(
[**PDGA 113200**](https://www.pdga.com/player/113200))  

Please feel free to contact me at the links provided on this website, or at the following address: Department of Hematology, Blegdamsvej 9, 2100 Copenhagen Ø, DK